version: "2"
services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs:ro
      - ./config/config.yml:/etc/docker/registry/config.yml
  
  auth:
    restart: always
    image: ouwen/docker_auth:latest
    ports: 
      - 5001:5001
    volumes:
      - ./config/auth_config.yml:/config/auth_config.yml:ro
      - ./logs:/logs
      - ./certs:/certs:ro

    command: ['-log_dir=/logs', '-alsologtostderr=true', '-stderrthreshold=ERROR', '/config/auth_config.yml']

  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    ports:
      - 5002:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://localhost:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=true
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
